name             'test-berkshelf'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures test-berkshelf'
long_description 'Installs/Configures test-berkshelf'
version          '0.1.0'
depends          'ruby_install', '~> 1.0.5'
